# Generated by Django 3.0.3 on 2020-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('P', 'Parent'), ('C', 'Child')], default='C', max_length=1),
        ),
    ]
