# Generated by Django 3.0.3 on 2020-02-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parent',
        ),
    ]
